-- Tariflere alt kategori atamaları
-- Önce add_recipe_subcategories.sql çalıştırılmış olmalı

-- ── ÇORBALAR ─────────────────────────────────────────────────────

UPDATE recipes SET subcategories = ARRAY['Bakliyat Çorbaları','Yöresel Çorbalar']       WHERE title = 'Acılı Ekşili Çorba';
UPDATE recipes SET subcategories = ARRAY['Bakliyat Çorbaları','Yöresel Çorbalar']       WHERE title = 'Analı Kızlı Çorbası';
UPDATE recipes SET subcategories = ARRAY['Et / Tavuk Sulu Çorbalar','Yöresel Çorbalar'] WHERE title = 'Arabaşı Çorbası';
UPDATE recipes SET subcategories = ARRAY['Yoğurtlu Çorbalar','Tahıllı Çorbalar']        WHERE title = 'Ayran Aşı Çorbası';
UPDATE recipes SET subcategories = ARRAY['Et / Tavuk Sulu Çorbalar']                    WHERE title = 'Balık Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Balkabağı Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları','Yöresel Çorbalar']          WHERE title = 'Bamya Çorbası';
UPDATE recipes SET subcategories = ARRAY['Et / Tavuk Sulu Çorbalar','Yöresel Çorbalar'] WHERE title = 'Beyran Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Brokoli Çorbası (Kremasız)';
UPDATE recipes SET subcategories = ARRAY['Tahıllı Çorbalar']                            WHERE title = 'Buğday Çorbası';
UPDATE recipes SET subcategories = ARRAY['Bakliyat Çorbaları']                          WHERE title = 'Çeşmi Nigar Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Domates Çorbası';
UPDATE recipes SET subcategories = ARRAY['Tahıllı Çorbalar']                            WHERE title = 'Domatesli Arpa Şehriye Çorbası';
UPDATE recipes SET subcategories = ARRAY['Yöresel Çorbalar']                            WHERE title = 'Dul Avrat Çorbası';
UPDATE recipes SET subcategories = ARRAY['Et / Tavuk Sulu Çorbalar','Yöresel Çorbalar'] WHERE title = 'Düğün Çorbası';
UPDATE recipes SET subcategories = ARRAY['Et / Tavuk Sulu Çorbalar']                    WHERE title = 'Ekşili Köfte Çorbası';
UPDATE recipes SET subcategories = ARRAY['Bakliyat Çorbaları','Tahıllı Çorbalar']       WHERE title = 'Erişteli Yeşil Mercimek Çorbası';
UPDATE recipes SET subcategories = ARRAY['Et / Tavuk Sulu Çorbalar']                    WHERE title = 'Et Suyu Çorbası';
UPDATE recipes SET subcategories = ARRAY['Bakliyat Çorbaları']                          WHERE title = 'Ezogelin Çorbası';
UPDATE recipes SET subcategories = ARRAY['Et / Tavuk Sulu Çorbalar']                    WHERE title = 'Gerdan Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Havuç Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Ispanak Çorbası';
UPDATE recipes SET subcategories = ARRAY['Et / Tavuk Sulu Çorbalar']                    WHERE title = 'İlikli Kemik Suyu Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları','Yöresel Çorbalar']          WHERE title = 'Kara Lahana Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Kereviz Çorbası';
UPDATE recipes SET subcategories = ARRAY['Bakliyat Çorbaları']                          WHERE title = 'Kırmızı Mercimek Çorbası';
UPDATE recipes SET subcategories = ARRAY['Et / Tavuk Sulu Çorbalar']                    WHERE title = 'Köfteli Çorba';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Köz Biber Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Köz Domates Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Köz Patlıcan Çorbası';
UPDATE recipes SET subcategories = ARRAY['Kremalı Çorbalar']                            WHERE title = 'Kremalı Brokoli Çorbası';
UPDATE recipes SET subcategories = ARRAY['Kremalı Çorbalar']                            WHERE title = 'Kremalı Mantar Çorbası';
UPDATE recipes SET subcategories = ARRAY['Kremalı Çorbalar']                            WHERE title = 'Kremalı Patates Çorbası';
UPDATE recipes SET subcategories = ARRAY['Kremalı Çorbalar','Et / Tavuk Sulu Çorbalar'] WHERE title = 'Kremalı Tavuk Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Lahana Çorbası';
UPDATE recipes SET subcategories = ARRAY['Yoğurtlu Çorbalar','Yöresel Çorbalar']        WHERE title = 'Lebeniye Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları','Yöresel Çorbalar']          WHERE title = 'Madımak Çorbası';
UPDATE recipes SET subcategories = ARRAY['Bakliyat Çorbaları']                          WHERE title = 'Mahluta Çorbası';
UPDATE recipes SET subcategories = ARRAY['Et / Tavuk Sulu Çorbalar','Tahıllı Çorbalar'] WHERE title = 'Mantı Çorbası';
UPDATE recipes SET subcategories = ARRAY['Tahıllı Çorbalar']                            WHERE title = 'Meksika Usulü Mısır Çorbası';
UPDATE recipes SET subcategories = ARRAY['Bakliyat Çorbaları']                          WHERE title = 'Mercimek Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Minestrone Çorbası';
UPDATE recipes SET subcategories = ARRAY['Yöresel Çorbalar']                            WHERE title = 'Muradiye Çorbası';
UPDATE recipes SET subcategories = ARRAY['Tahıllı Çorbalar']                            WHERE title = 'Ovmaç Çorbası';
UPDATE recipes SET subcategories = ARRAY['Et / Tavuk Sulu Çorbalar']                    WHERE title = 'Paça Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Pazı Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Pırasa Çorbası';
UPDATE recipes SET subcategories = ARRAY['Et / Tavuk Sulu Çorbalar']                    WHERE title = 'Salçalı Tavuk Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Sebze Çorbası';
UPDATE recipes SET subcategories = ARRAY['Yoğurtlu Çorbalar','Tahıllı Çorbalar']        WHERE title = 'Sıcak Ayran Aşı Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Soğan Çorbası';
UPDATE recipes SET subcategories = ARRAY['Soğuk Çorbalar','Yoğurtlu Çorbalar']          WHERE title = 'Soğuk Semizotu Çorbası';
UPDATE recipes SET subcategories = ARRAY['Kremalı Çorbalar']                            WHERE title = 'Sütlü Domates Çorbası';
UPDATE recipes SET subcategories = ARRAY['Kremalı Çorbalar']                            WHERE title = 'Sütlü Kabak Çorbası';
UPDATE recipes SET subcategories = ARRAY['Kremalı Çorbalar']                            WHERE title = 'Sütlü Mantar Çorbası';
UPDATE recipes SET subcategories = ARRAY['Tahıllı Çorbalar']                            WHERE title = 'Şehriye Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Taneli Sebze Çorbası';
UPDATE recipes SET subcategories = ARRAY['Yöresel Çorbalar']                            WHERE title = 'Tarhana Çorbası';
UPDATE recipes SET subcategories = ARRAY['Et / Tavuk Sulu Çorbalar']                    WHERE title = 'Tavuk Suyu Çorbası';
UPDATE recipes SET subcategories = ARRAY['Et / Tavuk Sulu Çorbalar','Sebze Çorbaları']  WHERE title = 'Tavuklu Sebze Çorbası';
UPDATE recipes SET subcategories = ARRAY['Et / Tavuk Sulu Çorbalar']                    WHERE title = 'Terbiyeli Tavuk Çorbası';
UPDATE recipes SET subcategories = ARRAY['Bakliyat Çorbaları','Yöresel Çorbalar']       WHERE title = 'Topalak Çorbası';
UPDATE recipes SET subcategories = ARRAY['Yoğurtlu Çorbalar','Tahıllı Çorbalar']        WHERE title = 'Toyga Çorbası';
UPDATE recipes SET subcategories = ARRAY['Tahıllı Çorbalar','Yöresel Çorbalar']         WHERE title = 'Tutmaç';
UPDATE recipes SET subcategories = ARRAY['Tahıllı Çorbalar']                            WHERE title = 'Un Çorbası';
UPDATE recipes SET subcategories = ARRAY['Sebze Çorbaları']                             WHERE title = 'Unsuz Domates Çorbası';
UPDATE recipes SET subcategories = ARRAY['Yoğurtlu Çorbalar']                           WHERE title = 'Yalancı İşkembe Çorbası';
UPDATE recipes SET subcategories = ARRAY['Yoğurtlu Çorbalar']                           WHERE title = 'Yayla Çorbası';
UPDATE recipes SET subcategories = ARRAY['Yoğurtlu Çorbalar','Tahıllı Çorbalar']        WHERE title = 'Yoğurtlu Buğday Çorbası';
UPDATE recipes SET subcategories = ARRAY['Tahıllı Çorbalar']                            WHERE title = 'Yoğurtsuz Yayla Çorbası';
UPDATE recipes SET subcategories = ARRAY['Et / Tavuk Sulu Çorbalar','Tahıllı Çorbalar'] WHERE title = 'Yüksük Çorbası';

-- ── ANA YEMEKLER ─────────────────────────────────────────────────

UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Sulu Yemekler']                                WHERE title = 'Acılı Et Sote';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri']                                                 WHERE title = 'Ali Nazik Kebabı';
UPDATE recipes SET subcategories = ARRAY['Balık / Deniz Ürünleri']                                       WHERE title = 'Balık Köftesi';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Fırın Yemekleri']                               WHERE title = 'Belen Tava';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Izgara / Mangal']                               WHERE title = 'Beyti Sarma';
UPDATE recipes SET subcategories = ARRAY['Sebze Yemekleri','Sulu Yemekler']                              WHERE title = 'Bezelye Yemeği';
UPDATE recipes SET subcategories = ARRAY['Sebze Yemekleri','Pilav / Tahıl Yemekleri']                   WHERE title = 'Bulgurlu Ispanak';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri']                                                 WHERE title = 'Çoban Kavurma';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri']                                                 WHERE title = 'Çökertme Kebabı';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Sebze Yemekleri','Sulu Yemekler']               WHERE title = 'Etli Bamya';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Dünya Mutfağı Yemekleri']                      WHERE title = 'Etli Fajita';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Sebze Yemekleri']                               WHERE title = 'Etli Kabak Dolması';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Sebze Yemekleri']                               WHERE title = 'Etli Kuru Patlıcan & Kuru Biber Dolması';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Sebze Yemekleri']                               WHERE title = 'Etli Lahana Sarması';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Fırın Yemekleri','Sulu Yemekler']               WHERE title = 'Etli Patlıcanlı Güveç';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Sulu Yemekler']                                 WHERE title = 'Etli Sulu Patates Yemeği';
UPDATE recipes SET subcategories = ARRAY['Bakliyat Yemekleri','Sulu Yemekler']                           WHERE title = 'Etsiz Nohut Yemeği';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Fast Food / Street Food']                       WHERE title = 'Ev Yapımı Tantuni';
UPDATE recipes SET subcategories = ARRAY['Fast Food / Street Food']                                      WHERE title = 'Evde Pratik Kumpir';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri','Fırın Yemekleri']                            WHERE title = 'Fırında Buffalo Soslu Kanat';
UPDATE recipes SET subcategories = ARRAY['Sebze Yemekleri','Fırın Yemekleri']                            WHERE title = 'Fırında Karnabahar Graten';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri','Fırın Yemekleri']                            WHERE title = 'Fırında Kaşarlı Tavuk';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Fırın Yemekleri']                               WHERE title = 'Fırında Köfte Patates';
UPDATE recipes SET subcategories = ARRAY['Balık / Deniz Ürünleri','Fırın Yemekleri']                    WHERE title = 'Fırında Levrek';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Fırın Yemekleri']                               WHERE title = 'Fırında Patlıcan Kebabı';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Fırın Yemekleri']                               WHERE title = 'Fırında Sebzeli Köfte';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri','Fırın Yemekleri']                            WHERE title = 'Fırında Sebzeli Tavuk';
UPDATE recipes SET subcategories = ARRAY['Balık / Deniz Ürünleri','Fırın Yemekleri']                    WHERE title = 'Fırında Somon';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri','Fırın Yemekleri']                            WHERE title = 'Fırında Soslu Tavuk Baget & Taze Otlu Patates';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri','Fırın Yemekleri']                            WHERE title = 'Fırında Tavuk Baget';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri','Fırın Yemekleri']                            WHERE title = 'Fırında Tavuk Şiş';
UPDATE recipes SET subcategories = ARRAY['Sebze Yemekleri','Fırın Yemekleri']                            WHERE title = 'Güveçte Mantar Sote';
UPDATE recipes SET subcategories = ARRAY['Balık / Deniz Ürünleri']                                       WHERE title = 'Hamsi Kuşu';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Fırın Yemekleri']                               WHERE title = 'Hasanpaşa Köfte';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri']                                                 WHERE title = 'Hünkar Beğendi';
UPDATE recipes SET subcategories = ARRAY['Sebze Yemekleri','Fırın Yemekleri']                            WHERE title = 'Ispanak Graten';
UPDATE recipes SET subcategories = ARRAY['Sebze Yemekleri']                                              WHERE title = 'İmam Bayıldı';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri']                                                 WHERE title = 'İslim Kebabı';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Fırın Yemekleri']                               WHERE title = 'İzmir Köfte';
UPDATE recipes SET subcategories = ARRAY['Sebze Yemekleri','Sulu Yemekler']                              WHERE title = 'Kabak Yemeği';
UPDATE recipes SET subcategories = ARRAY['Sebze Yemekleri','Fırın Yemekleri']                            WHERE title = 'Karnabahar Graten';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Sebze Yemekleri']                               WHERE title = 'Karnıyarık';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Fırın Yemekleri']                               WHERE title = 'Kaşarlı Fırın Köfte';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri']                                                 WHERE title = 'Kekikli Et Kavurma';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Sulu Yemekler']                                 WHERE title = 'Kıymalı Patates Yemeği';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri','Dünya Mutfağı Yemekleri']                   WHERE title = 'Köri Soslu Tavuk';
UPDATE recipes SET subcategories = ARRAY['Bakliyat Yemekleri','Sulu Yemekler']                           WHERE title = 'Kuru Fasulye';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Izgara / Mangal']                               WHERE title = 'Kuru Köfte';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Fırın Yemekleri']                               WHERE title = 'Kuzu İncikli Ankara Tava';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Fırın Yemekleri']                               WHERE title = 'Kuzu Tandır';
UPDATE recipes SET subcategories = ARRAY['Makarna / Noodle','Fırın Yemekleri','Dünya Mutfağı Yemekleri'] WHERE title = 'Lazanya';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri']                                              WHERE title = 'Mantarlı Tavuk Sote';
UPDATE recipes SET subcategories = ARRAY['Pilav / Tahıl Yemekleri']                                     WHERE title = 'Mantı';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Fırın Yemekleri']                               WHERE title = 'Patates Oturtma';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Sebze Yemekleri']                               WHERE title = 'Patlıcan Musakka';
UPDATE recipes SET subcategories = ARRAY['Sebze Yemekleri','Sulu Yemekler']                              WHERE title = 'Pazı Yemeği';
UPDATE recipes SET subcategories = ARRAY['Sebze Yemekleri','Pilav / Tahıl Yemekleri']                   WHERE title = 'Pırasa Diblesi';
UPDATE recipes SET subcategories = ARRAY['Sebze Yemekleri']                                              WHERE title = 'Portakallı Kereviz Yemeği';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri','Fırın Yemekleri']                            WHERE title = 'Sebzeli Kaşarlı Tavuk Güveç';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri','Dünya Mutfağı Yemekleri']                   WHERE title = 'Soya Soslu Ballı Tavuk';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Izgara / Mangal']                               WHERE title = 'Şiş Köfte';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Sulu Yemekler']                                 WHERE title = 'Tas Kebabı';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri','Dünya Mutfağı Yemekleri']                   WHERE title = 'Tavuk Fajita';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri','Pilav / Tahıl Yemekleri']                   WHERE title = 'Tavuk Kapama';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri','Dünya Mutfağı Yemekleri']                   WHERE title = 'Tavuk Schnitzel';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri']                                              WHERE title = 'Tavuk Sote';
UPDATE recipes SET subcategories = ARRAY['Makarna / Noodle']                                             WHERE title = 'Tavuklu Makarna';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri','Sulu Yemekler']                              WHERE title = 'Tavuklu Patates Yemeği';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri','Fırın Yemekleri']                            WHERE title = 'Tavuklu Sebzeli Güveç';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri']                                              WHERE title = 'Tavuklu Sultan Kebabı';
UPDATE recipes SET subcategories = ARRAY['Et Yemekleri','Fırın Yemekleri']                               WHERE title = 'Tepsi Kebabı';
UPDATE recipes SET subcategories = ARRAY['Tavuk Yemekleri','Fast Food / Street Food']                    WHERE title = 'Tiftik Tavuk Burger';
UPDATE recipes SET subcategories = ARRAY['Sebze Yemekleri','Sulu Yemekler']                              WHERE title = 'Türlü';
UPDATE recipes SET subcategories = ARRAY['Bakliyat Yemekleri']                                           WHERE title = 'Yeşil Mercimek';
UPDATE recipes SET subcategories = ARRAY['Sebze Yemekleri']                                              WHERE title = 'Zeytinyağlı Biber Dolması';
UPDATE recipes SET subcategories = ARRAY['Sebze Yemekleri']                                              WHERE title = 'Zeytinyağlı Enginar';
UPDATE recipes SET subcategories = ARRAY['Sebze Yemekleri']                                              WHERE title = 'Zeytinyağlı Taze Fasulye';

-- ── YARDIMCI LEZZETLER ───────────────────────────────────────────

UPDATE recipes SET subcategories = ARRAY['Mezeler']                          WHERE title = 'Acılı Ezme';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Anne Patatesi';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Arpa Şehriye Salatası';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Arpa Şehriyeli Bulgur Pilavı';
UPDATE recipes SET subcategories = ARRAY['Mezeler']                          WHERE title = 'Atom Mezesi';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Ballı Hardallı Patates Salatası';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Basmati Pirinç Pilavı';
UPDATE recipes SET subcategories = ARRAY['Hamur İşleri']                     WHERE title = 'Beşamel Soslu Fırın Makarna';
UPDATE recipes SET subcategories = ARRAY['Hamur İşleri']                     WHERE title = 'Beşamel Soslu Makarna';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Bulgur Pilavı';
UPDATE recipes SET subcategories = ARRAY['Mezeler']                          WHERE title = 'Cacık';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Caprese Salata';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Coleslaw Salatası';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Çilek Püreli Semizotu Salatası';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Çoban Salatası';
UPDATE recipes SET subcategories = ARRAY['Zeytinyağlılar']                   WHERE title = 'Deniz Börülcesi';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Dilim Zeytin Salatası';
UPDATE recipes SET subcategories = ARRAY['Hamur İşleri']                     WHERE title = 'Domates Soslu Makarna';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Domatesli Arpa Şehriye Pilavı';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Domatesli Bulgur Pilavı';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Domatesli Pirinç Pilavı';
UPDATE recipes SET subcategories = ARRAY['Hamur İşleri']                     WHERE title = 'Fırında İçli Köfte';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Fırında Kaşarlı Mantar';
UPDATE recipes SET subcategories = ARRAY['Zeytinyağlılar']                   WHERE title = 'Fırında Mücver';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Fırında Otlu Baby Patates';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Firik Pilavı';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Füme Etli Roka Salatası';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Garnitürlü Pirinç Pilavı';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Gavurdağı Salatası';
UPDATE recipes SET subcategories = ARRAY['Soslar']                           WHERE title = 'Guacamole Sos';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Haşlanmış Sebze';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Hatay Usulü Zahter Salatası';
UPDATE recipes SET subcategories = ARRAY['Mezeler']                          WHERE title = 'Havuç Tarator';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Havuçlu Şehriyeli Pirinç Pilavı';
UPDATE recipes SET subcategories = ARRAY['Mezeler']                          WHERE title = 'Haydari';
UPDATE recipes SET subcategories = ARRAY['Mezeler']                          WHERE title = 'Humus';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Kaburga Mısır';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Kaşık Salata';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Kısır';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Körili Pirinç Pilavı';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Közlenmiş Biber Salatası';
UPDATE recipes SET subcategories = ARRAY['Hamur İşleri']                     WHERE title = 'Kremalı Mantarlı Fettuccine';
UPDATE recipes SET subcategories = ARRAY['Hamur İşleri']                     WHERE title = 'Kremalı Penne Makarna';
UPDATE recipes SET subcategories = ARRAY['Mezeler']                          WHERE title = 'Kuru Cacık';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Kuru Domates Salatası';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Makarna Salatası';
UPDATE recipes SET subcategories = ARRAY['Mezeler']                          WHERE title = 'Mercimek Köftesi';
UPDATE recipes SET subcategories = ARRAY['Mezeler']                          WHERE title = 'Mor Lahana Tarator';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Narlı Semizotu Salatası';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Nohutlu Pirinç Pilavı';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Patates Püresi';
UPDATE recipes SET subcategories = ARRAY['Hamur İşleri']                     WHERE title = 'Patatesli Gül Böreği';
UPDATE recipes SET subcategories = ARRAY['Mezeler']                          WHERE title = 'Patlıcan Ezmesi';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Pirinç Pilavı';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Piyaz';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Portakallı Kereviz Salatası';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Roka Salatası';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Sebzeli Bulgur Pilavı';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Semizotu Salatası (Avokadolu)';
UPDATE recipes SET subcategories = ARRAY['Hamur İşleri']                     WHERE title = 'Su Böreği';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Sumaklı Soğan Salatası';
UPDATE recipes SET subcategories = ARRAY['Mezeler','Zeytinyağlılar']         WHERE title = 'Şakşuka';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Şalgamlı Kuskus Salatası';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Tahinli Piyaz';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Tel Şehriyeli Pirinç Pilavı';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Tereyağlı Bulgur Pilavı';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Tereyağlı Kuskus';
UPDATE recipes SET subcategories = ARRAY['Hamur İşleri']                     WHERE title = 'Tereyağlı Peynirli Erişte';
UPDATE recipes SET subcategories = ARRAY['Garnitürler']                      WHERE title = 'Tereyağlı Pirinç Pilavı';
UPDATE recipes SET subcategories = ARRAY['Turşular']                         WHERE title = 'Turşu Kavurma';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Yeşil Elmalı Semizotu Salatası';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Yeşil Salata';
UPDATE recipes SET subcategories = ARRAY['Salatalar']                        WHERE title = 'Yeşil Soğanlı Mevsim Salata';
UPDATE recipes SET subcategories = ARRAY['Mezeler']                          WHERE title = 'Yoğurtlu Havuç Salatası';
UPDATE recipes SET subcategories = ARRAY['Mezeler']                          WHERE title = 'Yoğurtlu Karamelize Soğan Mezesi';
UPDATE recipes SET subcategories = ARRAY['Hamur İşleri']                     WHERE title = 'Zerdeçallı Makarna';
UPDATE recipes SET subcategories = ARRAY['Zeytinyağlılar']                   WHERE title = 'Zeytinyağlı Börülce';

-- ── TATLILAR ─────────────────────────────────────────────────────

UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Bademli Puding';
UPDATE recipes SET subcategories = ARRAY['Pratik Tatlılar']                         WHERE title = 'Bisküvili Pasta';
UPDATE recipes SET subcategories = ARRAY['Çikolatalı Tatlılar']                     WHERE title = 'Brownie';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar','Çikolatalı Tatlılar']   WHERE title = 'Çikolatalı Magnolia';
UPDATE recipes SET subcategories = ARRAY['Çikolatalı Tatlılar','Fırın Tatlıları']  WHERE title = 'Çikolatalı Sufle';
UPDATE recipes SET subcategories = ARRAY['Meyveli Tatlılar','Dünya Tatlıları']      WHERE title = 'Çilekli Alman Pastası';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar','Meyveli Tatlılar']      WHERE title = 'Çilekli Magnolia';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar','Meyveli Tatlılar']      WHERE title = 'Çilekli Muhallebi';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Damla Sakızlı Muhallebi';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar','Hamur Tatlıları']    WHERE title = 'Dilber Dudağı';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar']                       WHERE title = 'Dondurmalı Kemalpaşa Tatlısı';
UPDATE recipes SET subcategories = ARRAY['Hamur Tatlıları']                         WHERE title = 'Elmalı Kurabiye';
UPDATE recipes SET subcategories = ARRAY['Fırın Tatlıları','Meyveli Tatlılar']     WHERE title = 'Elmalı Turta';
UPDATE recipes SET subcategories = ARRAY['Fırın Tatlıları']                         WHERE title = 'Fırın Helva';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar','Fırın Tatlıları']       WHERE title = 'Fırın Sütlaç';
UPDATE recipes SET subcategories = ARRAY['Meyveli Tatlılar','Dünya Tatlıları']      WHERE title = 'Frambuazlı Cheesecake';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Gelin Pastası';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Güllaç';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Hindistan Cevizli Sütlü Tatlı';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Höşmerim';
UPDATE recipes SET subcategories = ARRAY['Çikolatalı Tatlılar']                     WHERE title = 'Islak Kek';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar','Meyveli Tatlılar']   WHERE title = 'İncir Tatlısı';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'İncir Uyutması';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar']                       WHERE title = 'İrmik Helvası';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar','Hamur Tatlıları']    WHERE title = 'Kadayıf Dolması';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Kadayıflı Muhallebi';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar','Çikolatalı Tatlılar'] WHERE title = 'Kakaolu İrmik Helvası';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar','Hamur Tatlıları']    WHERE title = 'Kalburabastı';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Karamelli Flan';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar','Meyveli Tatlılar']   WHERE title = 'Kaymaklı Ayva Tatlısı';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Kazandibi';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar']                       WHERE title = 'Kemalpaşa Tatlısı';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Keşkül';
UPDATE recipes SET subcategories = ARRAY['Çikolatalı Tatlılar']                     WHERE title = 'Köstebek Pasta';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Krem Karamel';
UPDATE recipes SET subcategories = ARRAY['Çikolatalı Tatlılar']                     WHERE title = 'Krem Şokola';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar','Hamur Tatlıları']    WHERE title = 'Laz Böreği';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar','Meyveli Tatlılar']      WHERE title = 'Limonlu Magnolia';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Lotuslu Magnolia';
UPDATE recipes SET subcategories = ARRAY['Dünya Tatlıları']                         WHERE title = 'Medovik Pasta';
UPDATE recipes SET subcategories = ARRAY['Pratik Tatlılar','Çikolatalı Tatlılar']  WHERE title = 'Mozaik Pasta';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Muhallebili Kadayıf Tatlısı';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar','Meyveli Tatlılar']      WHERE title = 'Muzlu Magnolia';
UPDATE recipes SET subcategories = ARRAY['Meyveli Tatlılar']                        WHERE title = 'Muzlu Rulo Pasta';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar']                       WHERE title = 'Nevzine Tatlısı';
UPDATE recipes SET subcategories = ARRAY['Soğuk Tatlılar','Meyveli Tatlılar']      WHERE title = 'Orman Meyveli Parfe';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar','Dünya Tatlıları']       WHERE title = 'Panna Cotta';
UPDATE recipes SET subcategories = ARRAY['Soğuk Tatlılar','Meyveli Tatlılar']      WHERE title = 'Pişmeyen Limonlu Cheesecake';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar','Meyveli Tatlılar']   WHERE title = 'Portakallı Revani';
UPDATE recipes SET subcategories = ARRAY['Çikolatalı Tatlılar','Dünya Tatlıları']  WHERE title = 'Profiterol';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar']                       WHERE title = 'Revani';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Sakızlı Muhallebi';
UPDATE recipes SET subcategories = ARRAY['Dünya Tatlıları']                         WHERE title = 'San Sebastian Cheesecake';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar','Soğuk Tatlılar']     WHERE title = 'Soğuk Baklava';
UPDATE recipes SET subcategories = ARRAY['Pratik Tatlılar']                         WHERE title = 'Spoonful';
UPDATE recipes SET subcategories = ARRAY['Çikolatalı Tatlılar']                     WHERE title = 'Supangle';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Süt Helvası';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Sütlaç';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Sütlü İrmik Tatlısı';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar']                       WHERE title = 'Şekerpare';
UPDATE recipes SET subcategories = ARRAY['Çikolatalı Tatlılar']                     WHERE title = 'Şekersiz Brownie';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar','Yöresel Tatlılar']   WHERE title = 'Şıllık Tatlısı';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Tavuk Göğsü';
UPDATE recipes SET subcategories = ARRAY['Dünya Tatlıları']                         WHERE title = 'Tiramisu';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Trileçe';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar']                       WHERE title = 'Un Helvası';
UPDATE recipes SET subcategories = ARRAY['Şerbetli Tatlılar','Meyveli Tatlılar']   WHERE title = 'Vişneli Ekmek Kadayıfı';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Yalancı Tavuk Göğsü';
UPDATE recipes SET subcategories = ARRAY['Sütlü Tatlılar']                          WHERE title = 'Zerde';
